### PR TITLE
added new file, samuelf

### PR DESCRIPTION
**Pull request by tifany4me**
added new file, samuelf

### CODE REVIEW

**Review by cmuriukin — CHANGES_REQUESTED** [review]
Change the 1st line of code to Welcome to GitHub

**Review by hechichu — APPROVED** [review]
Looks Good, ready for merge!

**Review by cmuriukin — APPROVED** [review]
Great work code is ready for deployment to prod ill approve the merge

**Review by tifany4me — COMMENTED** [review]
Approved

**Review by tifany4me — COMMENTED** [review]
approved

**Review by tifany4me — COMMENTED** [review]
approved

**Review by cmuriukin — APPROVED** [review]

**Review by cmuriukin — APPROVED** [review]

**Review by cmuriukin — APPROVED** [review]

**Pull request merged**
